services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: predictdata
      POSTGRES_PASSWORD: predictdata
      POSTGRES_DB: predictdata
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 